"""Eliminar la restriccion de nombre unico de player

Revision ID: 86af33f74b32
Revises: 74c68e9fd3d1
Create Date: 2019-01-21 01:07:56.133830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86af33f74b32'
down_revision = '74c68e9fd3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_playername', table_name='player')
    op.create_index(op.f('ix_player_playername'), 'player', ['playername'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_playername'), table_name='player')
    op.create_index('ix_player_playername', 'player', ['playername'], unique=1)
    # ### end Alembic commands ###
