"""propietario en la tabla tournaments 36

Revision ID: a4314e777f4e
Revises: 
Create Date: 2019-01-24 01:43:31.400714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4314e777f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('surname1', sa.String(length=120), nullable=True),
    sa.Column('surname2', sa.String(length=120), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playername', sa.String(length=64), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdby'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_playername'), 'player', ['playername'], unique=False)
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('point_per_match', sa.Integer(), nullable=True),
    sa.Column('match_per_round', sa.Integer(), nullable=True),
    sa.Column('rounds_qty', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createdby'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_created'), 'tournament', ['created'], unique=False)
    op.create_index(op.f('ix_tournament_name'), 'tournament', ['name'], unique=False)
    op.create_table('PlayersByTournament',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tour'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id', 'tour')
    )
    op.create_index(op.f('ix_round_date'), 'round', ['date'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=True),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player2'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchdate', sa.DateTime(), nullable=True),
    sa.Column('tour', sa.Integer(), nullable=True),
    sa.Column('team1', sa.Integer(), nullable=True),
    sa.Column('team2', sa.Integer(), nullable=True),
    sa.Column('roundid', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['roundid'], ['round.id'], ),
    sa.ForeignKeyConstraint(['team1'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tour'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_matchdate'), 'match', ['matchdate'], unique=False)
    op.create_index(op.f('ix_match_team1'), 'match', ['team1'], unique=False)
    op.create_index(op.f('ix_match_team2'), 'match', ['team2'], unique=False)
    op.create_index(op.f('ix_match_tour'), 'match', ['tour'], unique=False)
    op.create_table('match_results_by_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('set1', sa.Integer(), nullable=True),
    sa.Column('set2', sa.Integer(), nullable=True),
    sa.Column('set3', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id', 'match_id', 'team')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results_by_team')
    op.drop_index(op.f('ix_match_tour'), table_name='match')
    op.drop_index(op.f('ix_match_team2'), table_name='match')
    op.drop_index(op.f('ix_match_team1'), table_name='match')
    op.drop_index(op.f('ix_match_matchdate'), table_name='match')
    op.drop_table('match')
    op.drop_table('team')
    op.drop_index(op.f('ix_round_date'), table_name='round')
    op.drop_table('round')
    op.drop_table('PlayersByTournament')
    op.drop_index(op.f('ix_tournament_name'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_created'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_player_playername'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
